// TEMPORARILY DISABLED: Firebase removed, using FastAPI backend
// This file is kept for reference only

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options are no longer used.
/// The app now uses FastAPI backend with SessionService for authentication.
class DefaultFirebaseOptions {
  // Disabled - Firebase removed
}
