// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwCyVlb5jfwM62vGJm9TT6daz_DLhIm0',
    appId: '1:834578953953:web:e1eaa4feb88193c7e9e9a0',
    messagingSenderId: '834578953953',
    projectId: 'alitaptap-500c9',
    authDomain: 'alitaptap-500c9.firebaseapp.com',
    storageBucket: 'alitaptap-500c9.firebasestorage.app',
    measurementId: 'G-E0C98G4CQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIrowIjEgFyNKSrmPcdWEX-0TP34suTfc',
    appId: '1:834578953953:android:6f4a058832e492c0e9e9a0',
    messagingSenderId: '834578953953',
    projectId: 'alitaptap-500c9',
    storageBucket: 'alitaptap-500c9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZwCyVlb5jfwM62vGJm9TT6daz_DLhIm0',
    appId: '1:834578953953:web:952deeda4c1b34aae9e9a0',
    messagingSenderId: '834578953953',
    projectId: 'alitaptap-500c9',
    authDomain: 'alitaptap-500c9.firebaseapp.com',
    storageBucket: 'alitaptap-500c9.firebasestorage.app',
    measurementId: 'G-HR2GWNT795',
  );
}
