name: alitaptap_mobile
description: ALITAPTAP — community problems to student research
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  image_picker: ^1.1.2
  maplibre_gl: ^0.25.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.2.0
  pdf: ^3.10.0
  path_provider: ^2.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.5.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/logo_source.png
  min_sdk_android: 21
  adaptive_icon_background: "#FFC700"
  adaptive_icon_foreground: assets/branding/logo_source.png
  web:
    generate: true
    image_path: assets/branding/logo_source.png
    background_color: "#FFC700"
    theme_color: "#FFC700"
  windows:
    generate: true
    image_path: assets/branding/logo_source.png
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo_source.png
    - assets/branding/mangrove_1.jpg
    - assets/branding/mangrove_2.jpg
    - assets/branding/peeltab_1.jpg
    - assets/branding/peeltab_2.jpg
    - assets/branding/peeltab_3.png
    - assets/branding/peeltab_4.jpg
